# @format

BOT: {
  OWNERS: ["1214959194294321202"],
  ADMINS: ["1214959194294321202"],
}
LINKS: {
  SUPPORT: "",
  MONGO_URI: "",
}
SPOTIFY: {
  ID: "",
  Secret: "",
}

MANAGER: {
  OWNER: "1297443880576225312",
  TOKEN: "",
  }

FUEGO: {
  PREFIX: "!",
  EMOJIS: "black",
  COLOR: "#3d16ca",
  SHARDS: 1,
  PER_CLUSTER: 1,
  TOKEN: "",
  TOPGGAUTH: "",
      }

WEBHOOKS: {
  ERROR: "",
  STATIC: "",
  PLAYER: "",
  SERVER: "",
  COMMAND: "",
}
